Solution1/Presentation/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models.ViewModels;
using DataAccess.Repositories;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Domain.Interfaces;

namespace Presentation.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly FlightRepository _flightRepository;
        //private readonly ITickets _ticketRepository;
        private readonly TicketRepository _ticketRepository;


        public AdminController(FlightRepository flightRepository, TicketRepository ticketRepository)
        {
            _flightRepository = flightRepository ?? throw new ArgumentNullException(nameof(flightRepository));
            _ticketRepository = ticketRepository ?? throw new ArgumentNullException(nameof(ticketRepository));
        }

        public IActionResult ShowFlights()
        {
            try { 
            // Retrieve all available flights
            var flights = _flightRepository.GetFlights().ToList();
            var flightViewModels = flights.Select(flight => new FlightsViewModels
            {
                Id = flight.Id,
                SeatRows = flight.SeatRows,
                SeatColumns = flight.SeatColumns,
                DepartureDate = flight.DepartureDate,
                ArrivalDate = flight.ArrivalDate,
                CountryFrom = flight.CountryFrom,
                CountryTo = flight.CountryTo,
                RetailPrice = CalculateRetailPrice(flight.WholesalePrice, flight.CommissionRate)
            }).ToList();

            return View(flightViewModels);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
        }
        private double CalculateRetailPrice(double wholesalePrice, double commissionRate)
        {
            const double RetailPricePercentage = 1.2;
            return wholesalePrice * RetailPricePercentage;
        }
        public IActionResult FlightDetails(Guid id)
        {
            var flight = _flightRepository.GetFlight(id);

            if (flight == null)
            {
                // Handle invalid flight
                return RedirectToAction("ShowFlights");
            }

            var detailedFlightViewModel = new DetailedFlightViewModel
            {
                Id = flight.Id,
                SeatRows = flight.SeatRows,
                SeatColumns = flight.SeatColumns,
                DepartureDate = flight.DepartureDate,
                ArrivalDate = flight.ArrivalDate,
                CountryFrom = flight.CountryFrom,
                CountryTo = flight.CountryTo,
                RetailPrice = CalculateRetailPrice(flight.WholesalePrice, flight.CommissionRate),
                FullyBooked = flight.FullyBooked,
            };

            return View(detailedFlightViewModel);
        }
        public IActionResult ShowAllTickets()
        {
            try { 
            // Retrieve all tickets
            var allTickets = _ticketRepository.GetAllTickets();

            // Map all tickets to view models
            var ticketViewModels = allTickets.Select(ticket => new TicketViewModel
            {
                Id = ticket.Id,
                SeatRow = ticket.SeatRow,
                SeatColumn = ticket.SeatColumn,
                FlightIdFK = ticket.FlightIdFK,
                Passport = ticket.Passport,
                PricePaid = ticket.PricePaid,
                Cancelled = ticket.Cancelled,
            }).ToList();

            // Pass the list of tickets to the view
            return View(ticketViewModels);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
        }


        public IActionResult DetailedTickets(Guid id)
        {
            var ticketDetails = _ticketRepository.GetTicketById(id);
            var viewModel = new DetailedTicketViewModel
            {
                Id = ticketDetails.Id,
                SeatRow = ticketDetails.SeatRow,
                SeatColumn = ticketDetails.SeatColumn,
                FlightIdFK = ticketDetails.FlightIdFK,
                Passport = ticketDetails.Passport,
                PassportImg = ticketDetails.PassportImg,
                PricePaid = ticketDetails.PricePaid,
                Cancelled = ticketDetails.Cancelled,
            };

            return View(viewModel);
        }
    }
}

Solution1/Presentation/Controllers/TicketController.cs
using DataAccess.Repositories;
using Domain.Interfaces;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models.ViewModels;
using System.Collections.Concurrent;
using System.ComponentModel.DataAnnotations.Schema;
using System.Net.Sockets;
using System.Security.Claims;

namespace Presentation.Controllers
{
    public class TicketsController : Controller
    {
        //private readonly ITickets _ticketRepository;
        private readonly TicketRepository _ticketRepository;
        private readonly FlightRepository _flightRepository;
        private readonly UserManager<CustomUser> _userManager;
        public TicketsController(TicketRepository ticketRepository, FlightRepository flightRepository, UserManager<CustomUser> userManager )
        {
            _userManager = userManager;
            _ticketRepository = ticketRepository ?? throw new ArgumentNullException(nameof(ticketRepository));
            _flightRepository = flightRepository ?? throw new ArgumentNullException(nameof(flightRepository));
        }
        public IActionResult ShowFlights()
        {
            var today = DateTime.Now.Date;

            // Retrieve all flights with a future departure date
            var flights = _flightRepository.GetFlights()
                .Where(f => f.DepartureDate >= today)
                .ToList();

            /* Filter flights that are not fully booked
            var filteredFlights = flights
            .Where(f => !f.FullyBooked)
            .ToList();*/

            // Map the filtered flights to view models, make fully booked unclickable
            var flightViewModels = flights.Select(flight => new FlightsViewModels
            {
                Id = flight.Id,
                SeatRows = flight.SeatRows,
                SeatColumns = flight.SeatColumns,
                DepartureDate = flight.DepartureDate,
                ArrivalDate = flight.ArrivalDate,
                CountryFrom = flight.CountryFrom,
                CountryTo = flight.CountryTo,
                RetailPrice = CalculateRetailPrice(flight.WholesalePrice, flight.CommissionRate)
            }).ToList();

            return View(flightViewModels);
        }

        private double CalculateRetailPrice(double wholesalePrice, double commissionRate)
        {
            const double RetailPricePercentage = 1.2;
            return wholesalePrice * RetailPricePercentage;
        }
        public IActionResult FlightDetails(Guid id)
        {
            var flight = _flightRepository.GetFlight(id);

            if (flight == null)
            {
                // Handle invalid flight
                return RedirectToAction("ShowFlights");
            }

            var detailedFlightViewModel = new DetailedFlightViewModel
            {
                Id = flight.Id,
                SeatRows = flight.SeatRows,
                SeatColumns = flight.SeatColumns,
                DepartureDate = flight.DepartureDate,
                ArrivalDate = flight.ArrivalDate,
                CountryFrom = flight.CountryFrom,
                CountryTo = flight.CountryTo,
                RetailPrice = CalculateRetailPrice(flight.WholesalePrice, flight.CommissionRate),
                FullyBooked = flight.FullyBooked,
            };

            return View(detailedFlightViewModel);
        }
        [HttpGet]
        //[authorize]
        public IActionResult CreateTicket(Guid flightId)
        {
            var flight = _flightRepository.GetFlight(flightId);

            if (flight == null)
            {
                // Handle invalid flight
                return RedirectToAction("ShowFlights");
            }
            var viewModel = new CreateTicketViewModel()
            {
                FlightIdFK = flightId,
                Flight = flight,
                price = CalculateRetailPrice(flight.WholesalePrice, flight.CommissionRate)
            };

            return View(viewModel);
        }

        [HttpPost]
        //[authorize]
        public IActionResult CreateTicket(CreateTicketViewModel viewModel, [FromServices] IWebHostEnvironment host)
        {
            string relativepath = "";
            try
            {

                string filename = Guid.NewGuid() + System.IO.Path.GetExtension(viewModel.PassImgFile.FileName);
                string absolutePath = host.WebRootPath+@"\images\"+filename;
                relativepath = @"/images/" + filename;
                using (FileStream fs = new FileStream(absolutePath, FileMode.CreateNew))
                {
                    viewModel.PassImgFile.CopyTo(fs);
                    fs.Flush();
                    fs.Close();
                }
                    _ticketRepository.Book(new Ticket()
                    {
                        SeatRow = viewModel.SeatRow,
                        SeatColumn = viewModel.SeatColumn,
                        FlightIdFK = viewModel.FlightIdFK,
                        Passport = viewModel.Passport,
                        PricePaid = viewModel.PricePaid,
                        Cancelled = viewModel.Cancelled,
                        PassportImg = relativepath
                    });
                TempData["message"] = "Product saved successfully";
                return RedirectToAction("ShowAllTickets");
            }
            catch (Exception ex)
            {
                TempData["error"] = "Product was not inserted successfully";
                return View(viewModel);
            }
        }
        [Authorize]
        public async Task<IActionResult> ShowAllTickets()//only showing one ticket
        {
            try {

                // Get the current user's passport number
                var currentUser = await _userManager.FindByEmailAsync(User.Identity.Name);



            // Retrieve tickets for the current user based on passport number
            var userTickets = _ticketRepository.GetTicketsByPassport(currentUser.Passportno).ToList();

            // Map tickets to view models
            var ticketViewModels = userTickets.Select(ticket => new TicketViewModel
            {
                Id = ticket.Id,
                SeatRow = ticket.SeatRow,
                SeatColumn = ticket.SeatColumn,
                FlightIdFK = ticket.FlightIdFK,
                Passport = ticket.Passport,
                PricePaid = ticket.PricePaid,
                Cancelled = ticket.Cancelled,
            }).ToList();

            return View(ticketViewModels);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index", "Home");
            }
        }
        public IActionResult DetailedTickets(Guid id)
        {
            var ticketDetails = _ticketRepository.GetTicketById(id);
            var viewModel = new DetailedTicketViewModel
            {
                Id = ticketDetails.Id,
                SeatRow = ticketDetails.SeatRow,
                SeatColumn = ticketDetails.SeatColumn,
                FlightIdFK = ticketDetails.FlightIdFK,
                Passport = ticketDetails.Passport,
                PassportImg = ticketDetails.PassportImg,
                PricePaid = ticketDetails.PricePaid,
                Cancelled = ticketDetails.Cancelled,
            };

            return View(viewModel);
        }
        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            // Retrieve the ticket by id and display the confirmation page
            var ticket = _ticketRepository.GetTicketById(id);
            var viewModel = new DetailedTicketViewModel
            {
                Id = ticket.Id,
                SeatRow = ticket.SeatRow,
                SeatColumn = ticket.SeatColumn,
                FlightIdFK = ticket.FlightIdFK,
                Passport = ticket.Passport,
                PricePaid = ticket.PricePaid,
                Cancelled = ticket.Cancelled,
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(Guid id)
        {
            // Cancel the ticket (update its status)
            _ticketRepository.CancelTicket(id);

            // Redirect to the ShowAllTickets page after deletion
            return RedirectToAction("ShowAllTickets");
        }
        public IActionResult GetSeatingPlan(Guid flightId)
        {
            // Retrieve flight details by ID
            var flight = _flightRepository.GetFlight(flightId);

            if (flight == null)
            {
                // Handle invalid flight ID
                return BadRequest("Invalid flight ID");
            }
            
            // Return a JSON object with seating plan details
            var seatingPlan = new
            {
                SeatRows = flight.SeatRows,
                SeatColumns = flight.SeatColumns
            };

            return Json(seatingPlan);
        }
    }
}

Solution1/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Airplane Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Airplane Booking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="ShowFlights">Show Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="ShowAllTickets">Show My Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ShowFlights">Admin Flights View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ShowAllTickets">Admin Tickets View</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if(TempData["message"] != null)
            {
                <div class="alert alert-primary" role="alert">
                    @TempData["message"].ToString()
                </div>
            }
            @if (TempData["error"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["error"].ToString()
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>